name: doptrack-estimate
channels:
  - conda-forge
  - anaconda
  - tudat-team/label/dev
  - tudat-team
dependencies:
  - cartopy
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pip:
    - git+https://github.com/DopTrack/process.git
  - scikit-learn
  - scipy
  - tudatpy
