name: doptrack-estimate
channels:
  - conda-forge
  - tudat-team/label/dev
dependencies:
  - cartopy
  - sgp4
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tudatpy
